[ERROR]: during executing: "openroad -exit -no_init -python /openlane/scripts/odbpy/diodes.py place --diode-cell sky130_fd_sc_hd__diode_2 --diode-pin DIODE --threshold Infinity --side-strategy source --port-protect 1 --input-lef /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/merged.nom.lef --output-def /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.def --output /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.odb /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/17-Lab4.odb |& tee /dev/null /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/logs/routing/19-io_diodes.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
OpenROAD b16bda7e82721d10566ff7e2b68f1ff0be9f9e38 
Features included (+) or not (-): +Charts +GPU +GUI +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Usage: diodes.py place [OPTIONS] INPUT_DB
Try 'diodes.py place --help' for help.

Error: Invalid value for '--port-protect': '1' is not one of 'none', 'in', 'out', 'both'.
child process exited abnormally

[ERROR]: Step 19 (routing) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 throw_error} CALL {try_exec openroad -exit -no_init -python /openlane/scripts/odbpy/diodes.py place --diode-cell sky130_fd_sc_hd__diode_2 --diode-pin DIODE --threshold Infinity --side-strategy source --port-protect 1 --input-lef /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/merged.nom.lef --output-def /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.def --output /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.odb /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/17-Lab4.odb |& tee /dev/null /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/logs/routing/19-io_diodes.log} CALL {run_odbpy_script /openlane/scripts/odbpy/diodes.py place --diode-cell sky130_fd_sc_hd__diode_2 --diode-pin DIODE --threshold Infinity --side-strategy source --port-protect 1 --input-lef /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/merged.nom.lef --output-def /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.def --output /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.odb /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/17-Lab4.odb |& tee /dev/null /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/logs/routing/19-io_diodes.log} CALL {manipulate_layout /openlane/scripts/odbpy/diodes.py place -indexed_log /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/logs/routing/19-io_diodes.log -output /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.odb -output_def /openlane/designs/RegisterFile/runs/RUN_2025.06.01_18.15.32/tmp/routing/19-io_diodes.def --diode-cell sky130_fd_sc_hd__diode_2 --diode-pin DIODE --threshold Infinity --side-strategy source --port-protect 1} CALL io_diode_insertion CALL run_routing CALL run_routing_step CALL {run_non_interactive_mode -design RegisterFile}} -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "try_exec" line 15)
    invoked from within
"try_exec $::env(OPENROAD_BIN) -exit -no_init -python {*}$args"
    (procedure "run_odbpy_script" line 3)
    invoked from within
"run_odbpy_script {*}$args  --input-lef $::env(MERGED_LEF)  --output-def $arg_values(-output_def)  --output $arg_values(-output)  $arg_values(-input)  ..."
    (procedure "manipulate_layout" line 19)
    invoked from within
"manipulate_layout $::env(SCRIPTS_DIR)/odbpy/diodes.py place -indexed_log [index_file $::env(routing_logs)/io_diodes.log] -output $save_odb -output_def..."
    (procedure "io_diode_insertion" line 11)
    invoked from within
"io_diode_insertion"
    (procedure "run_routing" line 13)
    invoked from within
"run_routing"
    (procedure "run_routing_step" line 7)
    invoked from within
"run_routing_step"} -errorline 1
[ERROR]: Failed to create manufacturability and metric reports:
[ERROR]: Traceback (most recent call last):
  File "/openlane/scripts/generate_reports.py", line 184, in <module>
    cli()
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/generate_reports.py", line 51, in cli
    report = Report(design, tag, design_name, params, run_path).get_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 809, in get_report
    *self.extract_all_values(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 359, in extract_all_values
    power_report = Artifact(
                   ^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 62, in __init__
    self.pathname = matches[0]
                    ~~~~~~~^^^
IndexError: list index out of range
[ERROR]: Flow failed.
